apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-crud-server-deployment-v1
  labels:
    app: simple-http-crud-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-http-crud-server
  template:
    metadata:
      labels:
        app: simple-http-crud-server
        version: v1
    spec:
      containers:
      - name: simple-http-crud-server
        image: arsenteroganisyan/otus-crud-server:v3.1
        ports:
        - containerPort: 8000
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: config
                key: port
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: config
                key: host
          - name: USER
            valueFrom:
              secretKeyRef:
                name: secret
                key: user
          - name: DB
            valueFrom:
              configMapKeyRef:
                name: config
                key: db
          - name: PASSWRORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: password